### ISSUE TITLE
Failed to import mod, returned null without setting error

### ISSUE THREAD

**Issue by grzekozl** [mopioid/Borderlands-Commander#33] opened 2022-06-28 20:57 UTC
Just installed (and reinstalled) commander, getting this error every time I boot up the game.
![image](https://user-images.githubusercontent.com/52246267/176286289-5adbd5df-e5e8-45fd-82ff-16761ac38cba.png)

**Comment by mopioid** [comment] 2023-10-22 06:53
Duplicate of  #34

**Closed by mopioid** 2023-10-22 06:53 UTC
