### ISSUE TITLE
Not there

### ISSUE THREAD

**Issue by LiaBobbi** [mopioid/Borderlands-Commander#29] opened 2021-02-26 20:07 UTC
In game when I go into the mods menu to turn on commander mod it just isn't there. I checked my mods folder in Win32 and the mod is there, but I can't access it in game.

**Comment by Darggeron** [comment] 2021-03-31 03:41
Same issue here, playing on Epic.

**Comment by mopioid** [comment] 2023-10-22 06:57
Duplicate of #31

**Closed by mopioid** 2023-10-22 06:57 UTC
